# name: Send MONUSDT Alert to Slack

# on:
#   schedule:
#     - cron: "0 */2 * * *"  # Every 2 hours
#   workflow_dispatch:  # Optional manual trigger

# jobs:
#   run-alert:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.11

#     - name: Install dependencies
#       run: |
#         pip install pandas requests pybit

#     - name: Run script
#       env:
#         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         BYBIT_API_KEY: ${{ secrets.BYBIT_API_KEY }}
#         BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
#       run: |
#         python bybit_recent_trade.py
